// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Trauma.Common.Knowledge;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Trauma.Client.Knowledge.UI;

[GenerateTypedNameReferences]
public sealed partial class ProficiencyTab : Control
{
    [Dependency] private IEntitySystemManager _system = default!;
    private readonly KnowledgeSystem _knowledge;

    public ProficiencyTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _knowledge = _system.GetEntitySystem<KnowledgeSystem>();
    }

    public void UpdateProficiencyTab(EntityUid player)
    {
        TabContainer.SetTabTitle(this, Loc.GetString("trauma-proficiency-title"));

        ProficiencyBox.RemoveAllChildren();
        ProficiencyPlaceholder.Visible = true;

        var proficiencies = _knowledge.GrabAllProficiencies(player);
        if (proficiencies == null || proficiencies.Count == 0)
            return;

        ProficiencyPlaceholder.Visible = false;
        ProficiencyBox.SeparationOverride = 6;

        foreach (var profInfo in proficiencies)
        {
            var control = new ProficiencyTabControl(profInfo);
            ProficiencyBox.AddChild(control);
        }
    }
}
