// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Trauma.Common.Knowledge;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Trauma.Client.Knowledge.UI;

[GenerateTypedNameReferences]
public sealed partial class ProficiencyTabControl : BoxContainer
{
    [Dependency] private IEntitySystemManager _system = default!;
    private readonly SpriteSystem _sprite;

    public ProficiencyTabControl(ProficiencyInfo info)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _system.GetEntitySystem<SpriteSystem>();

        if (info.Sprite != null)
            Icon.Texture = _sprite.Frame0(info.Sprite);

        ProficiencyName.Text = info.Name;
        ProficiencyLevel.Text = Loc.GetString($"proficiency-level");
    }
}
