// SPDX-License-Identifier: AGPL-3.0-or-later

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Trauma.Client.Knowledge.UI;

[GenerateTypedNameReferences]
public sealed partial class SpecializationControl : BoxContainer
{
    public event Action<bool>? OnToggle;
    public bool Purchased { get; private set; }
    public string SpecializationId { get; }
    private readonly int _cost;

    public SpecializationControl(string specializationId, string name, int cost)
    {
        RobustXamlLoader.Load(this);

        SpecializationId = specializationId;
        _cost = cost;

        SpecLabel.Text = name;
        CostLabel.Text = $"Cost: {_cost}";

        AcquireCheckBox.OnToggled += args =>
        {
            Purchased = args.Pressed;
            OnToggle?.Invoke(Purchased);
        };
    }

    public void SetState(bool acquired, bool isProficiencyMet)
    {
        Purchased = acquired && isProficiencyMet;
        AcquireCheckBox.Pressed = Purchased;
        AcquireCheckBox.Disabled = !isProficiencyMet;

        // Visual dimming when parent proficiency is missing
        var color = !isProficiencyMet ? Color.DimGray : (Purchased ? Color.White : Color.Gray);
        SpecLabel.Modulate = color;
        CostLabel.Modulate = color;
    }
}
