// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Trauma.Common.Knowledge;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Trauma.Client.Knowledge.UI;

[GenerateTypedNameReferences]
public sealed partial class TalentTab : Control
{
    [Dependency] private IEntitySystemManager _system = default!;
    private readonly KnowledgeSystem _knowledge;

    public TalentTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _knowledge = _system.GetEntitySystem<KnowledgeSystem>();
    }

    public void UpdateTalentTab(EntityUid player)
    {
        TabContainer.SetTabTitle(this, Loc.GetString("trauma-talent-title"));

        TalentBox.RemoveAllChildren();
        TalentPlaceholder.Visible = true;

        var talents = _knowledge.GrabAllTalents(player);
        if (talents == null || talents.Count == 0)
            return;

        TalentPlaceholder.Visible = false;
        TalentBox.SeparationOverride = 8;

        foreach (var talentInfo in talents)
        {
            var control = new TalentTabControl(talentInfo);
            TalentBox.AddChild(control);
        }
    }
}
