// SPDX-License-Identifier: AGPL-3.0-or-later

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Trauma.Client.Knowledge.UI;

[GenerateTypedNameReferences]
public sealed partial class TalentControl : BoxContainer
{
    public event Action<int>? OnChangeRank;

    public int Rank { get; private set; }
    private readonly int _baseCost;
    private readonly int _maxRank;

    public TalentControl(string name, int baseCost, int maxRank = 1)
    {
        RobustXamlLoader.Load(this);

        _baseCost = baseCost;
        _maxRank = maxRank;

        TalentLabel.Text = name;

        DecreaseButton.OnPressed += _ => OnChangeRank?.Invoke(-1);
        IncreaseButton.OnPressed += _ => OnChangeRank?.Invoke(+1);
    }

    public void SetRank(int rank)
    {
        Rank = Math.Clamp(rank, 0, _maxRank);
        var currentCost = Rank * _baseCost;

        RankLabel.Text = $"Rank: {Rank}/{_maxRank} (Cost: {currentCost})";
        DecreaseButton.Disabled = Rank <= 0;
        IncreaseButton.Disabled = Rank >= _maxRank;

        var color = Rank > 0 ? Color.White : Color.Gray;
        TalentLabel.Modulate = color;
        RankLabel.Modulate = color;
    }
}
