// SPDX-License-Identifier: AGPL-3.0-or-later

using System;
using Content.Trauma.Common.Knowledge;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Trauma.Client.Knowledge.UI;

public enum SpecializationCategory
{
    Speed,
    Attack,
    Defense,
    Damage
}

[GenerateTypedNameReferences]
public sealed partial class WeaponClassProficiencyControl : BoxContainer
{
    public event Action<int>? OnChangeProficiencyLevel;
    public event Action<SpecializationCategory, int>? OnChangeSpecializationAllocation;

    public int Level { get; private set; }
    public SpecializationAllocation Allocation { get; private set; }

    private readonly int _costPerLevel;
    private readonly int _maxLevel;
    private bool _specializationSupported = true;

    public WeaponClassProficiencyControl(string name, int costPerLevel, int maxLevel = 1)
    {
        RobustXamlLoader.Load(this);

        _costPerLevel = costPerLevel;
        _maxLevel = maxLevel;
        WeaponClassLabel.Text = name;

        DecreaseButton.OnPressed += _ => OnChangeProficiencyLevel?.Invoke(-1);
        IncreaseButton.OnPressed += _ => OnChangeProficiencyLevel?.Invoke(+1);

        // Bind 4-category specialization adjusters
        SpeedDecreaseButton.OnPressed += _ => OnChangeSpecializationAllocation?.Invoke(SpecializationCategory.Speed, -1);
        SpeedIncreaseButton.OnPressed += _ => OnChangeSpecializationAllocation?.Invoke(SpecializationCategory.Speed, +1);

        AttackDecreaseButton.OnPressed += _ => OnChangeSpecializationAllocation?.Invoke(SpecializationCategory.Attack, -1);
        AttackIncreaseButton.OnPressed += _ => OnChangeSpecializationAllocation?.Invoke(SpecializationCategory.Attack, +1);

        DefenseDecreaseButton.OnPressed += _ => OnChangeSpecializationAllocation?.Invoke(SpecializationCategory.Defense, -1);
        DefenseIncreaseButton.OnPressed += _ => OnChangeSpecializationAllocation?.Invoke(SpecializationCategory.Defense, +1);

        DamageDecreaseButton.OnPressed += _ => OnChangeSpecializationAllocation?.Invoke(SpecializationCategory.Damage, -1);
        DamageIncreaseButton.OnPressed += _ => OnChangeSpecializationAllocation?.Invoke(SpecializationCategory.Damage, +1);
    }

    public void SetSpecializationVisible(bool visible)
    {
        _specializationSupported = visible;
        UpdateSpecializationUI();
    }

    public void SetLevel(int level, int racialBase = 0)
    {
        Level = Math.Clamp(level, 0, _maxLevel);
        var added = Math.Max(Level - racialBase, 0);
        var cost = added * _costPerLevel;

        LevelLabel.Text = $"Proficiency: {Level}/{_maxLevel} (Cost: {cost})";
        DecreaseButton.Disabled = Level <= racialBase;
        IncreaseButton.Disabled = Level >= _maxLevel;

        var isProficient = Level > 0;
        var color = !isProficient ? Color.Gray : Color.White;
        LevelLabel.Modulate = color;
        WeaponClassLabel.Modulate = color;

        UpdateSpecializationUI();
    }

    public void SetSpecializationAllocation(SpecializationAllocation alloc)
    {
        Allocation = alloc;
        UpdateSpecializationUI();
    }

    private void UpdateSpecializationUI()
    {
        var isProficient = Level > 0;
        SpecializationsContainer.Visible = _specializationSupported && isProficient;

        if (!_specializationSupported)
            return;

        var speedCost = CalculateCategoryCost(Allocation.Speed);
        var attackCost = CalculateCategoryCost(Allocation.Attack);
        var defenseCost = CalculateCategoryCost(Allocation.Defense);
        var damageCost = CalculateCategoryCost(Allocation.Damage);

        SpeedLabel.Text = $"+{Allocation.Speed} (Cost: {speedCost})";
        AttackLabel.Text = $"+{Allocation.Attack} (Cost: {attackCost})";
        DefenseLabel.Text = $"+{Allocation.Defense} (Cost: {defenseCost})";
        DamageLabel.Text = $"+{Allocation.Damage} (Cost: {damageCost})";

        var minVal = Math.Min(Math.Min(Allocation.Speed, Allocation.Attack), Math.Min(Allocation.Defense, Allocation.Damage));

        SpeedDecreaseButton.Disabled = !isProficient || Allocation.Speed <= 0;
        SpeedIncreaseButton.Disabled = !isProficient || Allocation.Speed >= minVal + 1;

        AttackDecreaseButton.Disabled = !isProficient || Allocation.Attack <= 0;
        AttackIncreaseButton.Disabled = !isProficient || Allocation.Attack >= minVal + 1;

        DefenseDecreaseButton.Disabled = !isProficient || Allocation.Defense <= 0;
        DefenseIncreaseButton.Disabled = !isProficient || Allocation.Defense >= minVal + 1;

        DamageDecreaseButton.Disabled = !isProficient || Allocation.Damage <= 0;
        DamageIncreaseButton.Disabled = !isProficient || Allocation.Damage >= minVal + 1;
    }

    private int CalculateCategoryCost(int points)
    {
        if (points <= 0)
            return 0;

        return _costPerLevel * (points * (points + 1) / 2);
    }
}
